---
- hosts: all
  become: true
  vars:
    pubkey_path: "{{ lookup('env', 'SSH_PUBLIC_KEY_PATH') }}"
  roles:
    - { role: vitalk.secure-ssh, ssh_user: '{{ ansible_user }}', ssh_identity_key: '{{ pubkey_path }}' }
      
